"use client";

import { useMemo, useState } from "react";
import { Bell, CalendarDays, Check, ChevronRight, Download, FileText, Folder, LayoutDashboard, Mail, Search, Settings, SlidersHorizontal, Upload, UserRound, X } from "lucide-react";

type View = "dashboard" | "orders" | "schedule" | "files" | "settings";
type Stage = "디자인 1차" | "디자인 2-1" | "디자인 2-2" | "디자인 2-3" | "디자인 최종" | "최종 완료 및 인쇄";
type Project = { id:string; client:string; product:string; spec:string[]; stage:Stage; due:string; progress:number; contact:string; note:string; files:number };
const projects:Project[]=[
{id:"DPH-PJ-2606-018",client:"한빛초등학교",product:"졸업문집",spec:["A4","148p","무선제본"],stage:"디자인 1차",due:"06.19 15:00",progress:20,contact:"김** · se****@hanbit.es.kr",note:"표지 2종과 내지 일부 시안 구성 중",files:8},
{id:"DPH-PJ-2606-014",client:"네오브릿지",product:"사내 교육 교재",spec:["B5","96p","링제본"],stage:"디자인 2-2",due:"06.18 18:00",progress:60,contact:"박** · tr****@neobridge.co.kr",note:"전체 시안 오탈자 수정 2단계",files:13},
{id:"DPH-PJ-2606-027",client:"리버스랩",product:"제품 카탈로그",spec:["A5","40p","중철"],stage:"최종 완료 및 인쇄",due:"06.18 12:00",progress:100,contact:"최** · yu****@reverselab.io",note:"최종 확정 완료, 인쇄 진행",files:16},
{id:"DPH-PJ-2606-033",client:"온새미초등학교",product:"학교 소식지",spec:["A4","32p","중철"],stage:"디자인 2-1",due:"06.20 13:00",progress:40,contact:"이** · on****@onsami.es.kr",note:"전체 원고 반영 시안 준비",files:11},
{id:"DPH-PJ-2606-041",client:"브라이트랩",product:"브랜드 리플렛",spec:["A4 3단","2종","양면"],stage:"디자인 2-3",due:"06.21 17:00",progress:80,contact:"정** · br****@brightlab.kr",note:"인쇄 전 오탈자 수정 3단계",files:9},
{id:"DPH-PJ-2606-052",client:"해솔중학교",product:"교내 행사 포스터",spec:["A2","단면","컬러"],stage:"디자인 최종",due:"06.22 10:00",progress:90,contact:"문** · ha****@haesol.ms.kr",note:"최종 의견 확인 및 인쇄 파일 작업",files:7}];
const nav=[{id:"dashboard" as View,label:"대시보드",icon:LayoutDashboard},{id:"orders" as View,label:"주문관리",icon:FileText},{id:"schedule" as View,label:"일정표",icon:CalendarDays},{id:"files" as View,label:"파일함",icon:Folder},{id:"settings" as View,label:"설정",icon:Settings}];
const stageClass=(s:Stage)=>s==="최종 완료 및 인쇄"?"complete":s==="디자인 최종"?"final":s.startsWith("디자인 2")?"revision":"first";

export function PartnerWorkspace(){
 const [view,setView]=useState<View>("dashboard"),[selectedId,setSelectedId]=useState(projects[0].id),[filter,setFilter]=useState("전체"),[preview,setPreview]=useState(false);
 const selected=useMemo(()=>projects.find(p=>p.id===selectedId)??projects[0],[selectedId]);
 const filtered=filter==="전체"?projects:projects.filter(p=>p.stage.includes(filter));
 return <div className="dph-partner">
  <aside className="dph-sidebar"><div className="dph-brand"><span>D</span><div><strong>Design Print Hub</strong><small>디자이너 워크스페이스</small></div></div><nav>{nav.map(n=>{const Icon=n.icon;return <button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><Icon/><span>{n.label}</span></button>})}</nav><div className="dph-scope"><UserRound/><strong>배정 프로젝트 전용</strong><p>관리자가 배정한 프로젝트와 마스킹된 주문자 정보만 표시됩니다.</p></div><div className="dph-profile"><span>정</span><div><strong>정다온 디자이너</strong><small>협업 파트너</small></div></div></aside>
  <main className="dph-main"><header className="dph-head"><div><p>DESIGNER WORKSPACE</p><h1>{nav.find(n=>n.id===view)?.label}</h1><span>{view==="dashboard"?"배정받은 프로젝트의 진행 상황과 오늘 할 일을 확인합니다.":"배정 프로젝트만 조회하고 관리합니다."}</span></div><div className="dph-tools"><label><Search/><input aria-label="배정 프로젝트 검색" placeholder="기관명, 프로젝트 번호 검색"/><SlidersHorizontal/></label><button aria-label="알림"><Bell/><i>3</i></button></div></header>
   {view==="dashboard"&&<Dashboard selected={selected} visible={filtered} filter={filter} setFilter={setFilter} select={setSelectedId} open={()=>setView("orders")}/>}
   {view==="orders"&&<Orders selected={selected} select={setSelectedId} preview={()=>setPreview(true)}/>}
   {view==="schedule"&&<Schedule selected={selected} select={setSelectedId}/>}
   {view==="files"&&<Files selected={selected} select={setSelectedId}/>}
   {view==="settings"&&<WorkspaceSettings/>}
  </main>{preview&&<MailPreview project={selected} close={()=>setPreview(false)}/>}
 </div>
}
function Head({title,desc,children}:{title:string;desc?:string;children?:React.ReactNode}){return <div className="dph-card-head"><div><h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{children}</div>}
function ProjectRow({p,selected,select}:{p:Project;selected:boolean;select:(id:string)=>void}){return <button className={`dph-project-row ${selected?"selected":""}`} onClick={()=>select(p.id)}><span className="copy"><strong>{p.client} {p.product}</strong><small>{p.id}</small><span>{p.spec.map(s=><i key={s}>{s}</i>)}</span></span><span className="status"><strong>{p.note}</strong><small>마감 {p.due}</small></span><em className={`dph-stage ${stageClass(p.stage)}`}>{p.stage}</em><ChevronRight/></button>}
function Dashboard({selected,visible,filter,setFilter,select,open}:{selected:Project;visible:Project[];filter:string;setFilter:(v:string)=>void;select:(id:string)=>void;open:()=>void}){return <><section className="dph-metrics"><article><span>배정 프로젝트</span><strong>6</strong><small>진행 중 5건 · 완료 1건</small></article><article><span>48시간 내 마감</span><strong>3</strong><small>오늘 2건 · 내일 1건</small></article><article><span>수정 진행</span><strong>3</strong><small>2-1차부터 2-3차까지</small></article><article><span>이번 주 완료율</span><strong>83%</strong><small>계획 대비 정상 진행</small></article></section><div className="dph-dashboard"><section className="dph-card"><Head title="배정 프로젝트" desc="내게 배정된 작업만 단계별로 확인합니다."><div className="dph-filter">{["전체","1차","2차","최종"].map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v}</button>)}</div></Head><div className="dph-projects">{visible.map(p=><ProjectRow key={p.id} p={p} selected={selected.id===p.id} select={select}/>)}</div></section><Detail project={selected} open={open}/></div><section className="dph-card dph-today"><Head title="오늘의 작업" desc="마감과 회신 대기 순서로 정리했습니다."/><div><article><Mail/><span><strong>네오브릿지 2-2차 시안</strong><small>오늘 18:00 마감</small></span><em>작업 중</em></article><article><Bell/><span><strong>한빛초등학교 의견 대기</strong><small>1차 시안 발송 전 확인</small></span><em>확인 필요</em></article><article><Check/><span><strong>리버스랩 인쇄 이관</strong><small>최종 파일 전달 완료</small></span><em className="done">완료</em></article></div></section></>}
function Detail({project,open}:{project:Project;open:()=>void}){return <aside className="dph-card dph-detail"><Head title={`${project.client} ${project.product}`} desc="선택 프로젝트 상세"/><div className="dph-progress"><div><span>전체 진행률</span><strong>{project.progress}%</strong></div><i><b style={{width:`${project.progress}%`}}/></i></div><dl><div><dt>프로젝트 번호</dt><dd>{project.id}</dd></div><div><dt>현재 단계</dt><dd><em className={`dph-stage ${stageClass(project.stage)}`}>{project.stage}</em></dd></div><div><dt>마감 일정</dt><dd>{project.due}</dd></div><div><dt>연락 정보</dt><dd>{project.contact}</dd></div></dl><h3>작업 히스토리</h3><ol className="dph-history"><li className="done"><i><Check/></i><span><strong>프로젝트 배정</strong><small>관리자 배정 완료</small></span></li><li className="current"><i/><span><strong>{project.stage}</strong><small>{project.note}</small></span></li><li><i/><span><strong>다음 단계</strong><small>의견 회신 후 진행</small></span></li></ol><button className="dph-primary" onClick={open}>프로젝트 작업 열기 <ChevronRight/></button></aside>}
function Orders({selected,select,preview}:{selected:Project;select:(id:string)=>void;preview:()=>void}){return <div className="dph-orders"><section className="dph-card"><Head title="배정 주문관리" desc="주문 원문과 결제 정보 없이 작업 항목만 표시합니다."/><div className="dph-order-table"><div className="head"><span>프로젝트</span><span>제작 사양</span><span>현재 단계</span><span>마감</span></div>{projects.map(p=><button key={p.id} className={selected.id===p.id?"selected":""} onClick={()=>select(p.id)}><span><strong>{p.client}</strong><small>{p.product} · {p.id}</small></span><span>{p.spec.join(" · ")}</span><em className={`dph-stage ${stageClass(p.stage)}`}>{p.stage}</em><span>{p.due}</span></button>)}</div></section><aside className="dph-card dph-draft"><Head title="시안 발송 및 수정 소통" desc={`${selected.client} · ${selected.stage}`}/><label><span>받는 사람</span><input readOnly value={selected.contact}/></label><label><span>메일 제목</span><input className="subject" readOnly value={`[우리학교인쇄-${selected.client}] 안녕하세요, ${selected.stage} 시안 확인 부탁드립니다.`}/></label><label><span>메일 내용</span><textarea readOnly value={mailBody(selected.stage)}/></label><div className="dph-drop"><Upload/><strong>시안 또는 참고 이미지 첨부</strong><span>파일을 끌어다 놓거나 선택해 주세요.</span><button>파일 선택</button></div><button className="dph-primary" onClick={preview}>발송 화면 확인 <ChevronRight/></button></aside></div>}
function Schedule({selected,select}:{selected:Project;select:(id:string)=>void}){const days=["6월 18일 목","6월 19일 금","6월 20일 토","6월 21일 일","6월 22일 월"];return <section className="dph-card"><Head title="배정 프로젝트 일정표" desc="내가 맡은 디자인 일정만 표시합니다."/><div className="dph-calendar">{days.map((day,index)=><div key={day} className={index===0?"today":""}><header><strong>{day}</strong><span>{index===0?"오늘":`${projects.filter((_,i)=>i%5===index).length}건`}</span></header>{projects.filter((_,i)=>i%5===index).map(p=><button key={p.id} className={selected.id===p.id?"selected":""} onClick={()=>select(p.id)}><em className={`dph-stage ${stageClass(p.stage)}`}>{p.stage}</em><strong>{p.client}</strong><span>{p.product}</span><small>{p.due.split(" ")[1]}</small></button>)}</div>)}</div></section>}
function Files({selected,select}:{selected:Project;select:(id:string)=>void}){const names=["원고_마스킹본.zip",`${selected.client}_시안_v2.pdf`,"수정사항_취합본.pdf","인쇄용_최종파일.pdf"];return <div className="dph-files"><section className="dph-card dph-folders"><Head title="프로젝트 파일함" desc="배정 프로젝트별 파일을 확인합니다."/>{projects.map(p=><button key={p.id} className={selected.id===p.id?"selected":""} onClick={()=>select(p.id)}><Folder/><span><strong>{p.client}</strong><small>{p.product} · 파일 {p.files}개</small></span><ChevronRight/></button>)}</section><section className="dph-card"><Head title={`${selected.client} 파일`} desc={selected.id}><button className="dph-outline"><Upload/> 파일 올리기</button></Head><div className="dph-file-list">{names.map((name,index)=><div key={name}><FileText/><span><strong>{name}</strong><small>{index%2?"12.4 MB":"4.8 MB"}</small></span><em>{index===0?"원고":index===3?"최종":"시안"}</em><span>{index===0?"06.16":"오늘"}</span><button aria-label={`${name} 다운로드`}><Download/></button></div>)}</div></section></div>}
function WorkspaceSettings(){const [mail,setMail]=useState(true),[deadline,setDeadline]=useState(true);return <div className="dph-settings"><section className="dph-card"><Head title="워크스페이스 설정" desc="개인 화면과 알림 표시 방식을 설정합니다."/><div className="dph-setting-list"><Setting label="메일 회신 알림" desc="수정사항이 도착하면 알립니다." value={mail} change={()=>setMail(!mail)}/><Setting label="마감 일정 알림" desc="48시간 이내 마감을 강조합니다." value={deadline} change={()=>setDeadline(!deadline)}/><div><span><strong>개인정보 보호</strong><small>연락처와 이메일은 마스킹되어 표시됩니다.</small></span><em>관리자 정책</em></div></div></section><aside className="dph-card dph-account"><div>정</div><h2>정다온 디자이너</h2><p>외부 협업 파트너</p><dl><span><dt>접근 범위</dt><dd>배정 프로젝트만</dd></span><span><dt>표시 권한</dt><dd>마스킹 정보</dd></span><span><dt>관리자</dt><dd>Design Print Hub</dd></span></dl></aside></div>}
function Setting({label,desc,value,change}:{label:string;desc:string;value:boolean;change:()=>void}){return <div><span><strong>{label}</strong><small>{desc}</small></span><button className={value?"on":""} role="switch" aria-checked={value} onClick={change}><i/></button></div>}
function MailPreview({project,close}:{project:Project;close:()=>void}){return <div className="dph-modal-bg"><section className="dph-modal" role="dialog" aria-modal="true"><header><div><span>메일 발송 화면</span><h2>{project.client} 시안 메일</h2></div><button onClick={close} aria-label="닫기"><X/></button></header><dl><div><dt>받는 사람</dt><dd>{project.contact}</dd></div><div><dt>제목</dt><dd><strong>{`[우리학교인쇄-${project.client}] 안녕하세요, ${project.stage} 시안 확인 부탁드립니다.`}</strong></dd></div><div><dt>내용</dt><dd className="mail">{mailBody(project.stage)}</dd></div><div><dt>붙임파일</dt><dd><span className="dph-chip"><FileText/> {project.client}_시안.pdf</span></dd></div></dl><footer><button onClick={close}>내용 수정</button><button className="primary">발송하기</button></footer></section></div>}
function mailBody(stage:Stage){if(stage==="디자인 1차")return "안녕하세요, 우리학교인쇄입니다.\n전달주신 원고로 1차 디자인 시안을 회신드립니다. 디자인 컨셉 및 레이아웃 위주로 확인하실 수 있도록 일부 페이지만 작업하여 보내드리며, 시안 2종 보내드리니 하나를 선택 후 의견 회신 부탁드립니다.\n선택해주신 스타일로 전체 작업 진행 후 2차 전체 시안을 일정 맞춰 전달드리겠습니다.\n확인 부탁드립니다, 감사합니다.";if(stage==="디자인 2-1")return "안녕하세요 선생님, 우리학교인쇄입니다.\n원고 전체 작업하여 2차시안 보내드립니다.\n1. 누락이나 사진 오류, 오탈자 검수를 꼼꼼하게 부탁드립니다.\n2. 전체 시안 확인 후 오탈자 수정은 최대 3회까지 제공하고 있습니다.\n수정사항은 최대한 정리하여 한번에 메일로 보내주시길 부탁드립니다.\n감사합니다.";if(stage==="디자인 최종"||stage==="최종 완료 및 인쇄")return "안녕하세요 선생님, 우리학교인쇄입니다.\n최종 의견 반영 후 인쇄 전 최종 시안 보내드립니다.\n시안과 같이 인쇄 진행해도 될 지 최종 확인 후 확정 회신 주시면 제작 진행하겠습니다.\n확인 후 회신 부탁드립니다, 감사합니다.";return `안녕하세요 선생님, 우리학교인쇄입니다.\n수정사항 반영 후 ${stage.replace("디자인 ","")}차 시안 보내드립니다.\n1. 바쁘시겠지만 인쇄 전 오탈자 검수 꼼꼼하게 부탁드립니다.\n2. 수정 의견은 정리 및 취합하셔서 최대한 한번에 전달 부탁드립니다.\n확인 후 회신 부탁드립니다, 감사합니다.`;}
